#!/bin/bash
# .env から DEVELOPMENT_TEAM と API_SECRET を読み込み、xcodegen generate を実行するスクリプト
set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP_DIR="$REPO_ROOT/apps/ios"
ENV_FILE="$APP_DIR/.env"

if [ ! -f "$ENV_FILE" ]; then
  echo "Error: $ENV_FILE not found."
  echo "Create it with DEVELOPMENT_TEAM and API_SECRET:"
  echo "  DEVELOPMENT_TEAM=YOUR_TEAM_ID"
  echo "  API_SECRET=your-secret"
  exit 1
fi

source "$ENV_FILE"

# Sources/Secrets.swift を生成
cat > "$APP_DIR/Sources/Secrets.swift" <<SWIFT
// Auto-generated by generate-projects.sh — do not edit
enum Secrets {
    static let apiSecret = "${API_SECRET}"
}
SWIFT

# Widget/Secrets.swift を生成
cat > "$APP_DIR/Widget/Secrets.swift" <<SWIFT
// Auto-generated by generate-projects.sh — do not edit
enum Secrets {
    static let apiSecret = "${API_SECRET}"
}
SWIFT

# project.yml のプレースホルダーを置換して一時ファイルを作成
sed "s/DEVELOPMENT_TEAM_PLACEHOLDER/$DEVELOPMENT_TEAM/g" "$APP_DIR/project.yml" > "$APP_DIR/project.yml.resolved"

# xcodegen 実行
cd "$APP_DIR"
xcodegen generate --spec project.yml.resolved
rm project.yml.resolved

echo "✅ iOS project generated"
