name = "shoplist-api"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[[d1_databases]]
binding = "DB"
database_name = "shoplist-db"
database_id = "c54201dc-4ddf-413c-b212-8425feac3a88"
migrations_dir = "migrations"
